apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mylocal-global-cert
spec:
  secretName: mylocal-ingress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.mylocal.ing
    - app.mylocal.ing
    - shop.mylocal.ing
    - schedule.mylocal.ing
    - deliver.mylocal.ing
